version: '3.8'
services:
  app:
    image: ${DOCKER_USERNAME}/ripple
    container_name: ripple
    restart: always
    env_file:
      - .env.prod
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./data/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  redis-data:
