# 로컬 환경에서 사용할 설정 파일
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true  # 콘솔에 SQL 로그 출력
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 50
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    s3:
      bucket: ${BUCKET_ADDRESS}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_ACCESS_PASSWORD}

logging:
  level:
    root: INFO

Swagger:
  server:
    url: https://api.cotato-ripple.kro.kr